print(a, b, str1, sep='_______', end='\n\n')
print(a + (a > b))
print('The value of a is: ' + str(a))
print('The value of a is: {:*^20}'.format(str(a)))
print('The value of a is: %d' % a)
print('The value of a is: {:016,}, and the value of f2 is {:.6f}'.format(a, f2))
print(f'The value of a is: {a:016,}, and the value of f2 is {f2:.6f}')
print(f'The value of b in hex is {b:#X}, in octal {b:o}, in binary {b:09_b}, in decimal {b}')
print(f'Humidity is {0.7:.0%}')
print(f'g is {9.8:.2e}')
